# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nd_addfeature.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from qgis.PyQt import QtCore, QtGui, QtWidgets

_translate = QtCore.QCoreApplication.translate

class Ui_Nd_AddFeature(object):
    def setupUi(self, Nd_AddFeature):
        Nd_AddFeature.setObjectName("Nd_AddFeature")
        Nd_AddFeature.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        Nd_AddFeature.resize(449, 470)
        self.gridLayout = QtWidgets.QGridLayout(Nd_AddFeature)
        self.gridLayout.setObjectName("gridLayout")
        self.twPoints = QtWidgets.QTableWidget(Nd_AddFeature)
        self.twPoints.setObjectName("twPoints")
        self.twPoints.setColumnCount(2)
        self.twPoints.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.twPoints.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.twPoints.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.twPoints.setHorizontalHeaderItem(1, item)
        self.gridLayout.addWidget(self.twPoints, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Nd_AddFeature)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.rb_ProjectCrs = QtWidgets.QRadioButton(self.groupBox)
        self.rb_ProjectCrs.setChecked(True)
        self.rb_ProjectCrs.setObjectName("rb_ProjectCrs")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.rb_ProjectCrs)
        self.rb_LayerCrs = QtWidgets.QRadioButton(self.groupBox)
        self.rb_LayerCrs.setObjectName("rb_LayerCrs")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.rb_LayerCrs)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rb_OtherCrs = QtWidgets.QRadioButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_OtherCrs.sizePolicy().hasHeightForWidth())
        self.rb_OtherCrs.setSizePolicy(sizePolicy)
        self.rb_OtherCrs.setObjectName("rb_OtherCrs")
        self.horizontalLayout.addWidget(self.rb_OtherCrs)
        self.l_OtherCrsName = QtWidgets.QLabel(self.groupBox)
        self.l_OtherCrsName.setObjectName("l_OtherCrsName")
        self.horizontalLayout.addWidget(self.l_OtherCrsName)
        self.pb_ChooseCrs = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_ChooseCrs.sizePolicy().hasHeightForWidth())
        self.pb_ChooseCrs.setSizePolicy(sizePolicy)
        self.pb_ChooseCrs.setObjectName("pb_ChooseCrs")
        self.horizontalLayout.addWidget(self.pb_ChooseCrs)
        self.formLayout_2.setLayout(2, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout)
        self.gridLayout.addWidget(self.groupBox, 3, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Nd_AddFeature)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 4, 0, 1, 1)
        self.lblNumericalFeature = QtWidgets.QLabel(Nd_AddFeature)
        self.lblNumericalFeature.setObjectName("lblNumericalFeature")
        self.gridLayout.addWidget(self.lblNumericalFeature, 0, 0, 1, 1)
        self.addFromFileButton = QtWidgets.QPushButton(Nd_AddFeature)
        self.addFromFileButton.setObjectName("addFromFileButton")
        self.gridLayout.addWidget(self.addFromFileButton, 2, 0, 1, 1)

        self.retranslateUi(Nd_AddFeature)
        self.buttonBox.accepted.connect(Nd_AddFeature.accept)
        self.buttonBox.rejected.connect(Nd_AddFeature.reject)
        QtCore.QMetaObject.connectSlotsByName(Nd_AddFeature)

    def retranslateUi(self, Nd_AddFeature):
        Nd_AddFeature.setWindowTitle(_translate("Nd_AddFeature", u"Adicionar feicao numerica"))
        self.lblNumericalFeature.setText(_translate("Nd_AddFeature", u"Adicionar feicao numerica:"))
        item = self.twPoints.verticalHeaderItem(0)
        item.setText(_translate("Nd_AddFeature", "1"))
        item = self.twPoints.horizontalHeaderItem(0)
        item.setText(_translate("Nd_AddFeature", "X"))
        item = self.twPoints.horizontalHeaderItem(1)
        item.setText(_translate("Nd_AddFeature", "Y"))
        self.addFromFileButton.setText(_translate("Nd_AddFeature", u"Adicionar a partir de arquivo..."))
        self.groupBox.setTitle(_translate("Nd_AddFeature", u"Coordenadas sao fornecidas"))
        self.rb_ProjectCrs.setText(_translate("Nd_AddFeature", u"no sistema de referencia do projeto"))
        self.rb_LayerCrs.setText(_translate("Nd_AddFeature", u"no sistema de referencia da camada"))
        self.rb_OtherCrs.setText(_translate("Nd_AddFeature", u"em outro sistema de referencia"))
        self.l_OtherCrsName.setText(_translate("Nd_AddFeature", u"nao selecionado"))
        self.pb_ChooseCrs.setText(_translate("Nd_AddFeature", u"Selecionar"))
