# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\kretzer\Desktop\Git\EBGeo\EBGeo\ZoomCoordenadas\zoomCoord.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ZoomDockWidgetBase(object):
    def setupUi(self, ZoomDockWidgetBase):
        ZoomDockWidgetBase.setObjectName("ZoomDockWidgetBase")
        ZoomDockWidgetBase.resize(440, 109)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ZoomDockWidgetBase.sizePolicy().hasHeightForWidth())
        ZoomDockWidgetBase.setSizePolicy(sizePolicy)
        self.dockWidgetContents = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents.setSizePolicy(sizePolicy)
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/EBGeo/icons/zoomtool.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomToolButton = QtWidgets.QToolButton(self.dockWidgetContents)
        self.zoomToolButton.setObjectName("zoomToolButton")
        self.zoomToolButton.setIcon(icon)
        self.horizontalLayout.addWidget(self.zoomToolButton)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/plugins/EBGeo/icons/copyicon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CopyButton = QtWidgets.QToolButton(self.dockWidgetContents)
        self.CopyButton.setEnabled(True)
        self.CopyButton.setIcon(icon1)
        self.CopyButton.setObjectName("CopyButton")
        self.horizontalLayout.addWidget(self.CopyButton)
        self.SrcBox = QtWidgets.QComboBox(self.dockWidgetContents)
        self.SrcBox.setObjectName("SrcBox")
        self.horizontalLayout.addWidget(self.SrcBox)
        self.projSelector = QgsProjectionSelectionWidget(self.dockWidgetContents)
        self.projSelector.setObjectName("projSelector")
        self.horizontalLayout.addWidget(self.projSelector)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.coordTxt = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.coordTxt.setObjectName("coordTxt")
        self.verticalLayout.addWidget(self.coordTxt)
        ZoomDockWidgetBase.setWidget(self.dockWidgetContents)

        self.retranslateUi(ZoomDockWidgetBase)
        QtCore.QMetaObject.connectSlotsByName(ZoomDockWidgetBase)

    def retranslateUi(self, ZoomDockWidgetBase):
        _translate = QtCore.QCoreApplication.translate
        ZoomDockWidgetBase.setToolTip(_translate("ZoomDockWidgetBase", "Escolher Coordenada"))
        ZoomDockWidgetBase.setWindowTitle(_translate("ZoomDockWidgetBase", "Zoom para Coordenada"))
        self.zoomToolButton.setToolTip(_translate("ZoomDockWidgetBase", "Zoom para Coordenada"))
        self.zoomToolButton.setText(_translate("ZoomDockWidgetBase", "..."))
        self.CopyButton.setToolTip(_translate("ZoomDockWidgetBase", "Copiar Coordenada"))
        self.CopyButton.setText(_translate("ZoomDockWidgetBase", "..."))
from qgsprojectionselectionwidget import QgsProjectionSelectionWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ZoomDockWidgetBase = QtWidgets.QDockWidget()
    ui = Ui_ZoomDockWidgetBase()
    ui.setupUi(ZoomDockWidgetBase)
    ZoomDockWidgetBase.show()
    sys.exit(app.exec_())
