# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'profiletool.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from qgis.PyQt import QtCore, QtGui, QtWidgets
from qgis.gui import QgsMapLayerComboBox, QgsMapLayerProxyModel

_translate = QtCore.QCoreApplication.translate

class Ui_ProfileTool(object):
    def setupUi(self, ProfileTool):
        ProfileTool.setObjectName("ProfileTool")
        ProfileTool.resize(897, 356)
        self.dockWidgetContents = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents.setSizePolicy(sizePolicy)
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.activateButton = QtWidgets.QPushButton(self.dockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.activateButton.sizePolicy().hasHeightForWidth())
        self.activateButton.setSizePolicy(sizePolicy)
        self.activateButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.activateButton.setAutoFillBackground(False)
        self.activateButton.setCheckable(False)
        self.activateButton.setFlat(False)
        self.activateButton.setObjectName("activateButton")
        self.horizontalLayout_2.addWidget(self.activateButton)
        self.splitter = QtWidgets.QSplitter(self.dockWidgetContents)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.frame = QtWidgets.QFrame(self.splitter)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.sbMaxVal = QtWidgets.QDoubleSpinBox(self.frame)
        self.sbMaxVal.setKeyboardTracking(False)
        self.sbMaxVal.setMinimum(-99999.0)
        self.sbMaxVal.setMaximum(99999.0)
        self.sbMaxVal.setObjectName("sbMaxVal")
        self.verticalLayout_5.addWidget(self.sbMaxVal)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.sbMinVal = QtWidgets.QDoubleSpinBox(self.frame)
        self.sbMinVal.setKeyboardTracking(False)
        self.sbMinVal.setMinimum(-99999.0)
        self.sbMinVal.setMaximum(99999.0)
        self.sbMinVal.setObjectName("sbMinVal")
        self.verticalLayout_5.addWidget(self.sbMinVal)
        self.gridLayout_3.addLayout(self.verticalLayout_5, 0, 1, 1, 1)
        self.frame_for_plot = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_for_plot.sizePolicy().hasHeightForWidth())
        self.frame_for_plot.setSizePolicy(sizePolicy)
        self.frame_for_plot.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_for_plot.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_for_plot.setObjectName("frame_for_plot")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_for_plot)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_3.addWidget(self.frame_for_plot, 0, 0, 1, 1)
        self.widget_save_buttons = QtWidgets.QWidget(self.frame)
        self.widget_save_buttons.setObjectName("widget_save_buttons")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_save_buttons)
        self.horizontalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_reinitview = QtWidgets.QPushButton(self.widget_save_buttons)
        self.pushButton_reinitview.setObjectName("pushButton_reinitview")
        self.horizontalLayout_3.addWidget(self.pushButton_reinitview)
        spacerItem1 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_save_buttons)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.stackedWidget.addWidget(self.page)
        self.horizontalLayout_3.addWidget(self.stackedWidget)
        spacerItem2 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.cbxSaveAs = QtWidgets.QComboBox(self.widget_save_buttons)
        self.cbxSaveAs.setObjectName("cbxSaveAs")
        self.cbxSaveAs.addItem("")
        self.cbxSaveAs.addItem("")
        self.cbxSaveAs.addItem("")
        self.cbxSaveAs.addItem("")
        self.horizontalLayout_3.addWidget(self.cbxSaveAs)
        self.butSaveAs = QtWidgets.QPushButton(self.widget_save_buttons)
        self.butSaveAs.setObjectName("butSaveAs")
        self.horizontalLayout_3.addWidget(self.butSaveAs)
        self.gridLayout_3.addWidget(self.widget_save_buttons, 1, 0, 1, 2)
        self.frame_for_plot.raise_()
        self.widget_save_buttons.raise_()
        self.frame_2 = QtWidgets.QFrame(self.splitter)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.layerCombo = QgsMapLayerComboBox(self.frame_2)
        self.layerCombo.setFilters(QgsMapLayerProxyModel.Filter.RasterLayer)
        self.layerCombo.setObjectName("layerCombo")
        self.verticalLayout_2.addWidget(self.layerCombo)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.tableView = QtWidgets.QTableView(self.frame_2)
        self.tableView.setMinimumSize(QtCore.QSize(1, 1))
        self.tableView.setMaximumSize(QtCore.QSize(1, 1))
        self.tableView.setObjectName("tableView")
        self.verticalLayout_2.addWidget(self.tableView)
        self.groupBox = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setFrame(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.checkBox_mpl_tracking = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_mpl_tracking.setEnabled(True)
        self.checkBox_mpl_tracking.setChecked(True)
        self.checkBox_mpl_tracking.setObjectName("checkBox_mpl_tracking")
        self.verticalLayout_2.addWidget(self.checkBox_mpl_tracking)
        self.scrollArea = QtWidgets.QScrollArea(self.frame_2)
        self.scrollArea.setMaximumSize(QtCore.QSize(1, 1))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 16, 16))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.horizontalLayout_2.addWidget(self.splitter)
        ProfileTool.setWidget(self.dockWidgetContents)

        self.retranslateUi(ProfileTool)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ProfileTool)

    def retranslateUi(self, ProfileTool):
        ProfileTool.setWindowTitle(_translate("ProfileTool", "Analise do Perfil do Terreno"))
        self.activateButton.setText(_translate("ProfileTool", "A\n"
"t\n"
"i\n"
"v\n"
"a\n"
"r"))
        self.label_2.setText(_translate("ProfileTool", "maximo"))
        self.label_3.setText(_translate("ProfileTool", "minimo"))
        self.pushButton_reinitview.setText(_translate("ProfileTool", "Reenquadrar"))
        self.cbxSaveAs.setItemText(0, _translate("ProfileTool", "PDF"))
        self.cbxSaveAs.setItemText(1, _translate("ProfileTool", "PNG"))
        self.cbxSaveAs.setItemText(2, _translate("ProfileTool", "SVG"))
        self.cbxSaveAs.setItemText(3, _translate("ProfileTool", "print (PS)"))
        self.butSaveAs.setText(_translate("ProfileTool", "Salvar como"))
        self.label_4.setText(_translate("ProfileTool", "Camada com altimetria"))
        self.groupBox.setTitle(_translate("ProfileTool", "Opcoes"))
        self.label.setText(_translate("ProfileTool", "Modo de tracado"))
        self.comboBox.setItemText(0, _translate("ProfileTool", "Linha temporaria"))
        self.comboBox.setItemText(1, _translate("ProfileTool", "Linha selecionada"))
        self.checkBox_mpl_tracking.setText(_translate("ProfileTool", "Conectar posicao do cursor \n"
"com perfil tracado no mapa"))
